Repository iriteshmishra/Open-Source-Organization, pull requests merged in 2023-10, with the labels that each got.

#6 Added New Organizations for Open Source Contribution
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#7 added Github open source organization
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#22 Updated index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#31 Added the open source organisations.
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#32 add GirlScript Winter of Code
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#34 added "GNOME Foundation"
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#36 added swoc
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#37 Changes in CSS
  index.html
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#39 Add Flatcar Container Linux ( Fixes #38 )
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#41 Update index.html
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#46 Add Alibaba Summer of Code
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#49 added videoLAN to the organizations
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#51 update 📝 : Open Source Organisations
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#58 Update index.html
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#60 Added Software in the Public Interest in index.html
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#63 Added a new Open Source Program
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#65 Update index.html
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#48 Added BOSS program
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#71 Added new OpenSource org Charles
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#76 Add a new organization: All In
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#66 Update index.html
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#77 added the document foundation to the list
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#79 add LFN open source program
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#82 added owasp and fsf to index
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#83 Added LetsGrowMore Summer of Code
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#84 Update index.html
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#85 Implement of JSON data (FIX #80)
  data.json
  index.html
  script.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#89 [MODIFIED] : allignment of the why contribute section
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#90 added datadriven competitions
  data.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#92 2 winter season code added
  data.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#94 added Processing Foundations
  data.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#96 Added Dev Launchers to list
  data.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#98 Update index.html
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#99 Djangonaut Space Program
  data.json
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#97 Update data.json
  data.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
